#!/usr/bin/env sh
# Glasshound deployment setup script.
# Run once on a fresh server: sh scripts/deploy.sh
set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { printf "${GREEN}✓${NC}  %s\n" "$1"; }
warn() { printf "${YELLOW}!${NC}  %s\n" "$1"; }
die()  { printf "${RED}✗${NC}  %s\n" "$1"; exit 1; }

echo ""
echo "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo "${BOLD}║       Glasshound — Deploy Setup          ║${NC}"
echo "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Prerequisites check ───────────────────────────────────────────────────────
for cmd in docker; do
  command -v "$cmd" >/dev/null 2>&1 || die "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"
done
docker compose version >/dev/null 2>&1 || die "Docker Compose plugin not found. Install Docker Desktop or the compose plugin."
log "Docker OK"

# ── Helpers ───────────────────────────────────────────────────────────────────
gen_secret() {
  # 44-char URL-safe random string
  head -c 33 /dev/urandom | base64 | tr -d '=+/\n' | head -c 44
}

ask() {
  # ask VAR_NAME "Prompt text" "optional_default"
  _var="$1"; _prompt="$2"; _default="$3"
  if [ -n "$_default" ]; then
    printf "  %s [%s]: " "$_prompt" "$_default"
  else
    printf "  %s: " "$_prompt"
  fi
  read -r _input
  if [ -z "$_input" ] && [ -n "$_default" ]; then
    eval "$_var='$_default'"
  elif [ -n "$_input" ]; then
    eval "$_var='$_input'"
  else
    die "$_prompt is required."
  fi
}

# ── Gather config ─────────────────────────────────────────────────────────────
echo "Press ${BOLD}Enter${NC} to accept a default shown in [brackets].\n"

echo "${BOLD}── App ──────────────────────────────────────${NC}"
ask APP_URL      "Public URL (e.g. https://salon.yourdomain.com)" ""
ask HTTP_PORT    "Local port your proxy forwards to"              "8080"

echo ""
echo "${BOLD}── Database ─────────────────────────────────${NC}"
ask POSTGRES_PASSWORD "PostgreSQL password" "$(gen_secret)"

echo ""
echo "${BOLD}── Object storage (MinIO) ───────────────────${NC}"
ask MINIO_PASSWORD "MinIO password" "$(gen_secret)"

echo ""
echo "${BOLD}── Security ─────────────────────────────────${NC}"
_default_secret="$(gen_secret)"
ask SESSION_SECRET "Session secret (auto-generated)" "$_default_secret"

# ── Write .env ────────────────────────────────────────────────────────────────
cat > .env <<ENVFILE
# Generated by scripts/deploy.sh — keep this file private, never commit it.

APP_URL=${APP_URL}
APP_DOMAIN=localhost
HTTP_PORT=${HTTP_PORT}

POSTGRES_DB=glasshound
POSTGRES_USER=glasshound
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://glasshound:${POSTGRES_PASSWORD}@postgres:5432/glasshound?schema=public

REDIS_URL=redis://redis:6379

MINIO_ROOT_USER=glasshound
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
S3_ENDPOINT=http://minio:9000
S3_BUCKET=glasshound-assets
S3_ACCESS_KEY_ID=glasshound
S3_SECRET_ACCESS_KEY=${MINIO_PASSWORD}

SESSION_SECRET=${SESSION_SECRET}
ENVFILE

log ".env written"

# ── Build & start ─────────────────────────────────────────────────────────────
echo ""
echo "${BOLD}Building images and starting the stack…${NC}"
echo "(This takes a few minutes on first run.)"
echo ""

docker compose up -d --build
log "Stack started"

# ── Wait for healthy ──────────────────────────────────────────────────────────
echo ""
printf "Waiting for web container to become healthy"
TRIES=0
while [ $TRIES -lt 40 ]; do
  STATUS=$(docker compose ps --format json web 2>/dev/null | grep -o '"Health":"[^"]*"' | cut -d'"' -f4 || echo "")
  if [ "$STATUS" = "healthy" ]; then
    printf "\n"
    log "Web container healthy"
    break
  fi
  printf "."
  sleep 5
  TRIES=$((TRIES + 1))
done
if [ $TRIES -ge 40 ]; then
  warn "Timed out waiting for healthy. Check logs: docker compose logs web"
fi

# ── Optional: seed demo data ──────────────────────────────────────────────────
echo ""
printf "  Seed demo data? (nina@example.com account for client demos) [y/N]: "
read -r SEED_CHOICE
if [ "$SEED_CHOICE" = "y" ] || [ "$SEED_CHOICE" = "Y" ]; then
  echo "Seeding…"
  docker compose run --rm migrate npx tsx prisma/seed.ts
  log "Demo data seeded"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo "${BOLD}║           Deployment complete!            ║${NC}"
echo "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
echo "  App URL:      ${APP_URL}"
echo "  Health check: http://127.0.0.1:${HTTP_PORT}/api/health"
echo "  Demo login:   nina@example.com  /  demo-password  (if seeded)"
echo ""
echo "  Point your proxy at:  http://127.0.0.1:${HTTP_PORT}"
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f web     # live app logs"
echo "    docker compose ps              # service status"
echo "    docker compose pull && docker compose up -d --build   # update"
echo ""
